# Site
repository: bharatdeepmaan
# favicon: images/favicon.ico

# Personal info
name: Bharatdeep Maan
title: Problem Solver with a Vision
email: bharatdeep.maan@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  bharatdeepmaan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: bharatdeep.maan
linkedin_username: bharatmaan
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bharat and Iâ€™m currently a Plaksha Tech Leaders Fellow. I have experience in developing softwares, training ML models, analyzing data and building tech products. I have worked at HSBC for three years gaining teamwork and leadership skills. 
  
  I am most interested in <mark>Product Management</mark> that is developing innovative solutions which can solve real problems, provide value to customers and generate business opportunities. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Tech, Design and Business some of my other interests and hobbies are:
   - Sports Enthusiast 
   - Gaming
   

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
